### ISSUE TITLE
Ownership request of the PyPI package Mold

### ISSUE THREAD

**Issue by felix-hilden** [rhyselsmore/test#1]
Hi,
firstly sorry for contacting you in this random manner. I thought this would be the best way, because I believe that you are the same user as the PyPI account "r.elsmore"!

I've begun developing a Python project, which I'd like to call "Mold". It's a template Python project generator. However, as I'm sure you're aware, the project is currently claimed in 2013 to your account with no releases.

Would it be possible to transfer the ownership if you have no use for it? Looking forward to hearing from you! We can also discuss this elsewhere if you'd like.

BR,
Felix

**Comment by rhyselsmore** [comment]
Hi Felix,

Thanks for reaching out. I would be happy to transfer the package to you given it has no releases. 

What is your PyPi username?

Cheers,
Rhys

**Comment by rhyselsmore** [comment]
Hi Felix,

I've tracked you down on PyPi, and added you as an owner. Feel free to delete me once you get yourself added and setup.

Cheers,
Rhys

**Comment by felix-hilden** [comment]
Thank you so much for the fast response! I accepted the invitation and removed you as the owner.

Have a lovely day and all the best! 😃
Felix
